query appleValidate($userId: String, $receipt: String){
    appleValidate(userId: $userId, receipt: $receipt){
        code
        message
        data{
            isProcessed
            isValidated
            isCanceled
            isExpired
        }
    }
}