query getUserByMobile($mobile: String!){
    getUserByMobile(mobile: $mobile){
        code
        message
        data{
            id
            mobile
            nickname
            avatar
            status
            updateTime
            createTime
            balance
            role
        }
    }
}