query getWanderById($id: String!){
    getWanderById(id: $id){
        code
        message
        data{
            id
            background
            name
            description
            scenes
            price
            createTime
            updateTime
            author
            audio
            copy
            wanderAlbums
            status
            validTime
        }
    }
}