query loginByMobileAndPassword($mobile: String!, $password: String!){
    loginByMobileAndPassword(mobile: $mobile, password: $password){
        code
        message
        data{
            accessToken
            expiresIn
        }
    }
}