query searchMindfulnessAlbumRecord($page: Int!, $limit: Int!, $sort: String!, $favorite: Boolean, $boughtTime: [Int]){
    searchMindfulnessAlbumRecord(page: $page, limit: $limit, sort: $sort, favorite: $favorite, boughtTime: $boughtTime){
        code
        message
        data{
            id
            userId
            mindfulnessAlbumId
            favorite
            totalDuration
            longestDuration
            startCount
            finishCount
            lastStartTime
            lastFinishTime
            boughtTime
        }
    }
}