query searchMindfulnessAlbum($keyword: String, $page: Int, $limit: Int){
    searchMindfulnessAlbum(keyword: $keyword, page: $page, limit: $limit){
        code
        message
        data{
            total
            data{
                id
                background
                name
                description
                scenes
                price
                createTime
                updateTime
                author
                copy
                status
                validTime
            }
        }
    }
}